### ISSUE TITLE
bug: cargo doesn't know how to resolve dependencies for print-rcdom

### ISSUE THREAD

**Issue by coolaj86** [servo/html5ever#477]
See #476 

If you use `"*"` for the dependency version, cargo cannot resolve the versions correctly:

```toml
[dependencies]
html5ever = "*"
markup5ever_rcdom = "*"
```

Fix: use exact dependencies

```toml
[dependencies]
html5ever = "0.25.2"
markup5ever_rcdom = "0.1.0"
```

Not sure if this is a bug in how the versions have been published, or a bug in `cargo` itself.
